### ISSUE TITLE
Keycloak 502 proxy error

### ISSUE THREAD

**Issue by KenaiTheWolf** [bibbox/sys-bibbox#56]
Hello, 
After following the installation instructions, I have repeatedly gotten an error when going to sign into the panel to manage bibbox. 

Reproduction Steps:

1. Connect to the bibbox pannel (on my machine it is set up as bibbox.localhost )
2. Click the sign in button

Result:
1. Redirect begins and leads to the following error.
```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: DNS lookup failure for: bibbox-sys-commander-keycloak
```

While using docker stats to view the start up process, I can see the keycloak container start, spike in CPU utilization and the shut down and never restart.

Attached are the bibbox-sys-commander-backend, console logs as docker will not allow me to access keycloak's at this time.

Whaler (docker client) lists this as Bibbox-Sys which I believe to be a combined log of each of the bibbox images:
[bibbox-sys-commander-backend dump.txt](https://github.com/bibbox/sys-bibbox/files/12527751/bibbox-sys-commander-backend.dump.txt)

Bibbox-sys-commander-backend:
[bibbox-sys-commander-backend 2.txt](https://github.com/bibbox/sys-bibbox/files/12527796/bibbox-sys-commander-backend.2.txt)

Bibbox-sys-commander-celery:
[bibbox-sys-cellery.txt](https://github.com/bibbox/sys-bibbox/files/12527806/bibbox-sys-cellery.txt)

Trying to connect to other images with docker fails at this time. I am willing to provide further logs if needed.

**Comment by jungwire** [comment]
Hello Kenai,

Thanks for your message. 
We just merged a bugfix into the master branch that should fix that problem.
Please keep us updated whether this fixes you problem or not.

Best 
Emilian

**Comment by KenaiTheWolf** [comment]
Seems as though I'm still experiencing the same issue. Is there another log file I should be looking at to try to provide better information on how to resolve this?

**Comment by jungwire** [comment]
Okay thanks, don't worry I sure we find a solution.

Can you please test this:
`cd /opt/bibbox/sys-bibbox/`
`docker-compose -f docker-compose.dev.yml up --build -d`

if it does not work can you check with `docker ps` which container are running/restarting constantly. It seems like the master-FDP (FAIR DATA Point) can not start properly because of the mongoDB (maybe the mongoDB is not runing).

If there conatiners that start but then stop I would be interessed in those logs and also in the logs of the conatiners that are constantly restarting.

Just to be sure would you check if the following ports are free (accept for the bibbox conatiners), this is probably unrelated to your current problem but might cause problems down the line:
Ports:
- 80
- 443
- 5010
- 5011
- 5432
- 6379
- 5012
- 5013
- 5014
- 8080
- 8088

**Comment by KenaiTheWolf** [comment]
Running the docker command seems to have resolved the issue with keycloak. It's up and running now, all I need is to find the initial username and password so I can continue configuring. Thank you for your help!

**Comment by KenaiTheWolf** [comment]
I'm now seeing a new error - using the tempadmin credentials to sign in I immediately get Error Code: 0 HTTP failure response for bibbox.localhost/api/v1/usees: 0 Unknown error.

**Comment by jungwire** [comment]
Hi 
so a colleague set up arch machine in order to test it their. 
In the meantime:

how did you set up your local dns with which URL?

Can you check the database?
```
http://api.localhost/ or instead of localhost the local dns you set up
go to the adminer (http://127.0.0.1:5012/)
login 
System: PostgreSQL
Server: bibbox-sys-commander-postgres
Username: postgres
Password: postgres (unless you changed it in the docker-compose.dev.yml)
```
There should be a bibbox and a keycloak database. can you check if both of the filled with data.

**Comment by KenaiTheWolf** [comment]
Sorry its been a while, I haven't had time to work on this - I can check again soon.
